import Head from 'next/head';
import {BsFillMoonStarsFill} from 'react-icons/bs';
import {AiFillLinkedin,AiFillGithub} from 'react-icons/ai';
import Image from "next/image";
import design from '../public/design.png';
import code from '../public/code.png';
import consulting from '../public/consulting.png';
import web1 from '../public/web1.png';
import web2 from '../public/web2.png';
import web3 from '../public/web3.png';
import web4 from '../public/web4.png';
import web5 from '../public/web5.png';
import web6 from '../public/web6.png';
import { useState } from 'react';

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  
  return (
    <div className= {darkMode ? "dark" : ""}>
      <Head>
        <title>Ryan Murphy Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-white px-10  md:px-20 lg:px-40 dark:bg-gray-900'>
        <section className='h-screen'>
          <nav className='py-10 mb-12 flex justify-between bg-gradient-to-r from-cyan-300 to-teal-500 '>
            <h1 className='text-2xl font-mono'>developedbyed</h1>
            <ul className='flex items-center'>
              <li>
                <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className='cursor-pointer text-2xl'/>
              </li>
              <li>
                <a className=' bg-gradient-to-r from-cyan-300 to-teal-500 text-xl px-4 py-2 rounded-md ml-8' href="#">Resume</a>
                </li>
            </ul>
          </nav>
          <div className=' text-center p-10'>
            <h2 className='text-5xl py-2 text-teal-600 font-medium md:text-6xl lg:text-20xl '>Ryan Murphy</h2>
            <h3 className=' text-2xl py-2  dark:text-white'>Software Engineer</h3>
            <p className=' text-md py-5 leading-8 text-gray-800 md:text-xl max-w-xl mx-auto dark:text-white'>
            Some text here fa asf 
            asfsa fsafsa 
            fsafsafsafsafsafsa</p>
          </div>
          <div className='text-5xl flex justify-center gap-16 py-3 text-gray-800 dark:text-white'>
            <AiFillLinkedin />
            <AiFillGithub />
          </div>
         
        </section>
        {/* second page */}
        <section>
          <div className=' text-center p-10'>
            <h3 className='text-3xl py-1 dark:text-white'>Projects I Have Worked On</h3>
            <p className='text-md py-2 leading-8 text-gray-800 dark:text-white'>
              some randome text here that i <span className=' text-teal-500'>highligted </span>will fill later on
            </p>
          </div>

          <div className='lg:flex gap-10 justify-center'>
            <div className=' text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white'>
              <Image src = {design} width = {100} height = {100}/>
              <h3 className=' text-lg font-medium pt-8 pb-2'>Beutiful designs</h3>
              <p className='text-md py-2 leading-8 text-gray-800'>
                ad AD ADAj  J DJkj dJ  kjfjhakd as dasd asd asd 
              </p>
            </div>
            <div className=' text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white'>
              <Image src = {code} width = {100} height = {100}/>
              <h3 className=' text-lg font-medium pt-8 pb-2'>code</h3>
              <p className='text-md py-2 leading-8 text-gray-800'>
                ad AD ADAj  J DJkj dJ  kjfjhakd as dasd asd asd 
              </p>
            </div>
            <div className=' text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white'>
              <Image src = {consulting} width = {100} height = {100}/>
              <h3 className=' text-lg font-medium pt-8 pb-2'>other</h3>
              <p className='text-md py-2 leading-8 text-gray-800'>
                ad AD ADAj  J DJkj dJ  kjfjhakd as dasd asd asd 
              </p>
            </div>
          </div>

        </section>
        <section>
          <div>
            <h3 className='text-3xl py-1 dark:text-white'>Portfolio</h3>
            <p className='text-md py-2 leading-8 text-gray-800 dark:text-white'>
              some randome text here that i <span className=' text-teal-500'>highligted </span>will fill later on
            </p>

          </div>
          <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap className = "basis"'>
            <div className = "basis-1/3 flex-1"><Image src= {web1} className='rounded-lg object-cover' width = {'100%'} height = {'100%'} layout = "responsive" /></div>
            <div className = "basis-1/3 flex-1"><Image src= {web2} className='rounded-lg object-cover' width = {'100%'} height = {'100%'} layout = "responsive"  /></div>
            <div className = "basis-1/3 flex-1"><Image src= {web3} className='rounded-lg object-cover' width = {'100%'} height = {'100%'} layout = "responsive"  /></div>
            <div className = "basis-1/3 flex-1"><Image src= {web4} className='rounded-lg object-cover' width = {'100%'} height = {'100%'} layout = "responsive"  /></div>
            <div className = "basis-1/3 flex-1"><Image src= {web5} className='rounded-lg object-cover' width = {'100%'} height = {'100%'} layout = "responsive"  /></div>
            <div className = "basis-1/3 flex-1"><Image src= {web6} className='rounded-lg object-cover' width = {'100%'} height = {'100%'} layout = "responsive"  /></div>
          </div>
        </section>
      </main>      
    </div>
  );
}
